package cn.demo.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-06T16:55:32.614+08:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://webService.demo.cn/", name = "WeatherService")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherService {

    @WebMethod
    @RequestWrapper(localName = "query", targetNamespace = "http://webService.demo.cn/", className = "cn.demo.webservice.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://webService.demo.cn/", className = "cn.demo.webservice.QueryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String query(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
