package protoc.object;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProtocStruMsg.proto

public final class TestProtocStruMsg {
  private TestProtocStruMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestProtocStruOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string value1 = 1;
    /**
     * <code>required string value1 = 1;</code>
     */
    boolean hasValue1();
    /**
     * <code>required string value1 = 1;</code>
     */
    String getValue1();
    /**
     * <code>required string value1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getValue1Bytes();

    // required int32 value2 = 2;
    /**
     * <code>required int32 value2 = 2;</code>
     */
    boolean hasValue2();
    /**
     * <code>required int32 value2 = 2;</code>
     */
    int getValue2();

    // required bool value3 = 3;
    /**
     * <code>required bool value3 = 3;</code>
     */
    boolean hasValue3();
    /**
     * <code>required bool value3 = 3;</code>
     */
    boolean getValue3();
  }
  /**
   * Protobuf type {@code TestProtocStru}
   */
  public static final class TestProtocStru extends
      com.google.protobuf.GeneratedMessage
      implements TestProtocStruOrBuilder {
    // Use TestProtocStru.newBuilder() to construct.
    private TestProtocStru(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestProtocStru(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestProtocStru defaultInstance;
    public static TestProtocStru getDefaultInstance() {
      return defaultInstance;
    }

    public TestProtocStru getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestProtocStru(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value1_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value2_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value3_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestProtocStruMsg.internal_static_TestProtocStru_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestProtocStruMsg.internal_static_TestProtocStru_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestProtocStru.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TestProtocStru> PARSER =
        new com.google.protobuf.AbstractParser<TestProtocStru>() {
      public TestProtocStru parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestProtocStru(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TestProtocStru> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string value1 = 1;
    public static final int VALUE1_FIELD_NUMBER = 1;
    private Object value1_;
    /**
     * <code>required string value1 = 1;</code>
     */
    public boolean hasValue1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string value1 = 1;</code>
     */
    public String getValue1() {
      Object ref = value1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValue1Bytes() {
      Object ref = value1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 value2 = 2;
    public static final int VALUE2_FIELD_NUMBER = 2;
    private int value2_;
    /**
     * <code>required int32 value2 = 2;</code>
     */
    public boolean hasValue2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 value2 = 2;</code>
     */
    public int getValue2() {
      return value2_;
    }

    // required bool value3 = 3;
    public static final int VALUE3_FIELD_NUMBER = 3;
    private boolean value3_;
    /**
     * <code>required bool value3 = 3;</code>
     */
    public boolean hasValue3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool value3 = 3;</code>
     */
    public boolean getValue3() {
      return value3_;
    }

    private void initFields() {
      value1_ = "";
      value2_ = 0;
      value3_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasValue1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getValue1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, value3_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getValue1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, value3_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TestProtocStru parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestProtocStru parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestProtocStru parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestProtocStru parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestProtocStru parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestProtocStru parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TestProtocStru parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TestProtocStru parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TestProtocStru parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestProtocStru parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TestProtocStru prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestProtocStru}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TestProtocStruOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestProtocStruMsg.internal_static_TestProtocStru_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestProtocStruMsg.internal_static_TestProtocStru_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestProtocStru.class, Builder.class);
      }

      // Construct using TestProtocStruMsg.TestProtocStru.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value3_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestProtocStruMsg.internal_static_TestProtocStru_descriptor;
      }

      public TestProtocStru getDefaultInstanceForType() {
        return TestProtocStru.getDefaultInstance();
      }

      public TestProtocStru build() {
        TestProtocStru result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestProtocStru buildPartial() {
        TestProtocStru result = new TestProtocStru(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value1_ = value1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value2_ = value2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value3_ = value3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestProtocStru) {
          return mergeFrom((TestProtocStru)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestProtocStru other) {
        if (other == TestProtocStru.getDefaultInstance()) return this;
        if (other.hasValue1()) {
          bitField0_ |= 0x00000001;
          value1_ = other.value1_;
          onChanged();
        }
        if (other.hasValue2()) {
          setValue2(other.getValue2());
        }
        if (other.hasValue3()) {
          setValue3(other.getValue3());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasValue1()) {
          
          return false;
        }
        if (!hasValue2()) {
          
          return false;
        }
        if (!hasValue3()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestProtocStru parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestProtocStru) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string value1 = 1;
      private Object value1_ = "";
      /**
       * <code>required string value1 = 1;</code>
       */
      public boolean hasValue1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string value1 = 1;</code>
       */
      public String getValue1() {
        Object ref = value1_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value1_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string value1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValue1Bytes() {
        Object ref = value1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          value1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value1 = 1;</code>
       */
      public Builder setValue1(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value1 = 1;</code>
       */
      public Builder clearValue1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value1_ = getDefaultInstance().getValue1();
        onChanged();
        return this;
      }
      /**
       * <code>required string value1 = 1;</code>
       */
      public Builder setValue1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }

      // required int32 value2 = 2;
      private int value2_ ;
      /**
       * <code>required int32 value2 = 2;</code>
       */
      public boolean hasValue2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 value2 = 2;</code>
       */
      public int getValue2() {
        return value2_;
      }
      /**
       * <code>required int32 value2 = 2;</code>
       */
      public Builder setValue2(int value) {
        bitField0_ |= 0x00000002;
        value2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value2 = 2;</code>
       */
      public Builder clearValue2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value2_ = 0;
        onChanged();
        return this;
      }

      // required bool value3 = 3;
      private boolean value3_ ;
      /**
       * <code>required bool value3 = 3;</code>
       */
      public boolean hasValue3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool value3 = 3;</code>
       */
      public boolean getValue3() {
        return value3_;
      }
      /**
       * <code>required bool value3 = 3;</code>
       */
      public Builder setValue3(boolean value) {
        bitField0_ |= 0x00000004;
        value3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool value3 = 3;</code>
       */
      public Builder clearValue3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value3_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TestProtocStru)
    }

    static {
      defaultInstance = new TestProtocStru(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TestProtocStru)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TestProtocStru_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestProtocStru_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027TestProtocStruMsg.proto\"@\n\016TestProtocS" +
      "tru\022\016\n\006value1\030\001 \002(\t\022\016\n\006value2\030\002 \002(\005\022\016\n\006v" +
      "alue3\030\003 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TestProtocStru_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TestProtocStru_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TestProtocStru_descriptor,
              new String[] { "Value1", "Value2", "Value3", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
