package cn.it1995.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-11T14:51:04.885+08:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://service.it1995.cn/", name = "MyService")
@XmlSeeAlso({ObjectFactory.class})
public interface MyService {

    @WebMethod
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://service.it1995.cn/", className = "cn.it1995.service.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://service.it1995.cn/", className = "cn.it1995.service.GetRolesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cn.it1995.service.MyRoleArray getRoles()
;

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://service.it1995.cn/", className = "cn.it1995.service.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://service.it1995.cn/", className = "cn.it1995.service.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
