package cn.it1995.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-11T14:51:04.925+08:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "MyServiceService",
                  wsdlLocation = "http://127.0.0.1/MyService?wsdl",
                  targetNamespace = "http://service.it1995.cn/")
public class MyServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.it1995.cn/", "MyServiceService");
    public final static QName MyServicePort = new QName("http://service.it1995.cn/", "MyServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1/MyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1/MyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MyServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServicePort")
    public MyService getMyServicePort() {
        return super.getPort(MyServicePort, MyService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServicePort")
    public MyService getMyServicePort(WebServiceFeature... features) {
        return super.getPort(MyServicePort, MyService.class, features);
    }

}
