
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServiceImpl", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://webservice/", className = "webservice.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://webservice/", className = "webservice.QueryResponse")
    @Action(input = "http://webservice/WeatherServiceImpl/queryRequest", output = "http://webservice/WeatherServiceImpl/queryResponse")
    public String query(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
